version: '2.29'
services:
  backend:
    build:
      context: ./RealEstateAPISln
      dockerfile: RealEstateAPI/Dockerfile
    ports:
      - "8080:80"
    environment:
      - AzureBlobConnectionString=${AZURE_BLOB_CONNECTION_STRING}
      - AzureKeyVaultUrl=${AZURE_KEY_VAULT_URL}
      - TwilioAccountSid=${TWILIO_ACCOUNT_SID}
      - TwilioAuthToken=${TWILIO_AUTH_TOKEN}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}

    networks:
      - my-network
    env_file:
      - .env
    # depends_on:
    #   - sqlserver
  frontend:
    build:
      context: ./real-estate-app-fe
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    networks:
      - my-network
  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server
  #   environment:
  #     SA_PASSWORD: "YourStrong@Passw0rd"
  #     ACCEPT_EULA: "Y"
  #   ports:
  #     - "1433:1433"
networks:
  my-network:
    driver: bridge

# version: '3.4'

# services:
#   realestateapi:
#     image: ${DOCKER_REGISTRY-}realestateapi
#     build:
#       context: .
#       dockerfile: RealEstateAPI/Dockerfile
#   sqlserver:
#     image: mcr.microsoft.com/mssql/server
#     environment:
#         SA_PASSWORD: "YourStrong@Passw0rd"
#         ACCEPT_EULA: "Y"
#     ports:
#         - "1433:1433"

