name: Build and deploy ASP.Net Core app to Azure Web App - 67acres-webapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ./RealEstateAPISln/RealEstateAPI # Specify the directory containing the .csproj file

      - name: dotnet publish
        run: dotnet publish -c Release -o ./RealEstateAPISln/RealEstateAPI/publish
        working-directory: ./RealEstateAPISln/RealEstateAPI # Specify the directory containing the .csproj file

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./RealEstateAPISln/RealEstateAPI/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3EA1DEF569114C84BCE036FAFC6D3DEF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_459AD8754F474AF99A24570519EBBDA1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_35EFE6F0AFA54579A77ED83F9F6F25D2 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: '67acres-webapp'
          slot-name: 'Production'
          package: ./RealEstateAPISln/RealEstateAPI/publish
